# Generated by Django 2.2 on 2021-02-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=250, null=True)),
                ('to_be_taken_age', models.IntegerField(choices=[(1, 'Birth'), (2, '6 weeks'), (3, '10 weeks'), (4, '14 weeks'), (5, ' 6 months'), (6, '7 months'), (7, '9 months'), (8, '12 months'), (9, '13 months'), (10, '15 months'), (11, '16-18 months'), (12, '18 months'), (13, '4 - 6 years'), (14, '9 years'), (15, '9 years 6 months'), (16, '10 years')], default=1)),
                ('to_be_taken_by', models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Both', max_length=20)),
                ('Added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=250, null=True)),
                ('child_gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default='---', max_length=250)),
                ('date_of_birth', models.DateField()),
                ('child_age_integer', models.IntegerField(default=1)),
                ('child_age_attributes', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Year', 'Year')], default='---', max_length=20)),
                ('child_age_in_days', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Parent')),
            ],
        ),
    ]
