# Generated by Django 2.2 on 2021-02-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_age_integer',
        ),
    ]
