# Generated by Django 2.2 on 2021-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_child_child_age_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_age_integer',
            field=models.IntegerField(default=1),
        ),
    ]
