# Generated by Django 2.2 on 2021-02-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_child_child_age_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_age_attributes',
        ),
        migrations.RemoveField(
            model_name='child',
            name='child_age_in_days',
        ),
        migrations.RemoveField(
            model_name='child',
            name='child_age_integer',
        ),
        migrations.RemoveField(
            model_name='child',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='Added_on',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='to_be_taken_age',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='to_be_taken_by',
        ),
    ]
