# Generated by Django 2.2 on 2021-02-16 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210216_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_age_attributes',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Year', 'Year')], default='---', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='child_age_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='child_age_integer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='Added_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='to_be_taken_age',
            field=models.IntegerField(choices=[(1, 'Birth'), (2, '6 weeks'), (3, '10 weeks'), (4, '14 weeks'), (5, ' 6 months'), (6, '7 months'), (7, '9 months'), (8, '12 months'), (9, '13 months'), (10, '15 months'), (11, '16-18 months'), (12, '18 months'), (13, '4 - 6 years'), (14, '9 years'), (15, '9 years 6 months'), (16, '10 years')], default=1),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='to_be_taken_by',
            field=models.CharField(choices=[('Both', 'Both'), ('Boys', 'Boys'), ('Girls', 'Girls')], default='Both', max_length=20),
        ),
    ]
