# Generated by Django 2.2 on 2021-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210216_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='to_be_taken_age',
            field=models.CharField(choices=[(1, 'Birth'), (2, '6 weeks'), (3, '10 weeks'), (4, '14 weeks'), (5, ' 6 months'), (6, '7 months'), (7, '9 months'), (8, '12 months'), (9, '13 months'), (10, '15 months'), (11, '16-18 months'), (12, '18 months'), (13, '4 - 6 years'), (14, '9 years'), (15, '9 years 6 months'), (16, '10 years')], default='Birth', max_length=20),
        ),
    ]
