# Generated by Django 2.2 on 2021-02-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210216_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='to_be_taken_age',
        ),
    ]
